#!/usr/bin/env python3
#GABRIEL BASTOS VARGAS, 2017
#Instituto Federal do Rio de Janeiro
import subprocess    
import os
import time

datadir = os.environ["HOME"]+"/.config/maptoggle/"
if not os.path.exists(datadir):
    os.makedirs(datadir)
workspace_data = datadir+"wspacedata_"

def get_wlist():
    res = get_res()
    try:
        wlist = [l.split() for l in subprocess.check_output(["wmctrl", "-lG"]).decode("utf-8").splitlines()]
        #print(wlist)
        return [w for w in wlist if all([
            0 < int(w[2]) < res[0],
            0 < int(w[3]) < res[1],
            "_NET_WM_WINDOW_TYPE_NORMAL" in subprocess.check_output(["xprop", "-id", w[0]]).decode("utf-8"),
            ])]
    except subprocess.CalledProcessError:
        pass

def get_all():
    res = get_res()
    try:
        wlist = [l.split() for l in subprocess.check_output(["wmctrl", "-lG"]).decode("utf-8").splitlines()]
        #print('DENTRO DO GET_ALL...')
        #print(wlist)
        return [w for w in wlist if all([
            "_NET_WM_WINDOW_TYPE_NORMAL" in subprocess.check_output(["xprop", "-id", w[0]]).decode("utf-8"),
            ])]
    except subprocess.CalledProcessError:
        pass

def get_res():
    # get resolution
    xr = subprocess.check_output(["xrandr"]).decode("utf-8").split()
    pos = xr.index("current")
    return [int(xr[pos+1]), int(xr[pos+3].replace(",", "") )]

def current():
    # get the current viewport
    res = get_res()
    vp_data = subprocess.check_output(["wmctrl", "-d"]).decode("utf-8").split()
    dt = [int(n) for n in vp_data[3].split("x")]
    cols = int(dt[0]/res[0])
    curr_vpdata = [int(n) for n in vp_data[5].split(",")]
    curr_col = int(curr_vpdata[0]/res[0])+1
    curr_row = int(curr_vpdata[1]/res[1])
    return str(curr_col+curr_row*cols)

def toggle():
    try:
        f = workspace_data+current()
        #print(f)
        wlist = eval(open(f).read().strip())
        if  len(wlist) == 0:
            raise Exception('Sem programa no workspace')
        #print("Encontrado")
        #print("VOLTA WORKSPACE ")
        #print(current())
        #print(wlist)
        all_windows = get_all()
        for w in all_windows:
            subprocess.Popen(["xdotool", "windowunmap", w[0]])
        for w in wlist:
            subprocess.Popen(["xdotool", "windowmap", w[0]])
    except:
        current_windows = get_wlist()
        all_windows = get_all()
        open(f, "wt").write(str(current_windows))
        #print("Não encontrado")
        #print(current_windows)
        #print('DENTRO DO TOGGLE...')
        #print(all_windows)
        #print ('APAGA TUDO')
        for w in all_windows:
            subprocess.Popen(["xdotool", "windowunmap", w[0]])

for (dirpath, dirnames, filenames) in os.walk(datadir):
    for file in filenames:
        f = dirpath+file
        #print(f)
        os.remove(f)

atual = current()
print('Workspace inicial: ')
print(atual)
f = workspace_data+current()
current_windows = get_wlist()
open(f, "wt").write(str(current_windows))
tempo = time.time()
while True:
    if atual != current():
        print ('Mudou para o Workspace: ')
        atual = current()
        print (atual)
        toggle()
    if time.time() - tempo >= 1:
        f = workspace_data+current()
        current_windows = get_wlist()
        os.remove(f)
        open(f, "wt").write(str(current_windows))
